import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            alignContent: "center",
            justifyContent: "center",
            display: "flex",
            padding: "1rem",
            backgroundColor: "#3d3d3d",
            boxShadow: "0 0 1rem rgba(0, 0, 0, 0.5)",
          }}
        >
          Hello from layout
        </div>
        {children}
      </body>
    </html>
  );
}
